# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaxtackAgent < Formula
  desc "The Daxtack Enterprise Agent"
  homepage "https://daxtack.com"
  version "1.0.0-next"
  license "Copyright (c) Daxtack Inc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ankit-py/daxtack-agent/releases/download/v1.0-rc1/daxtack-agent_Darwin_x86_64.tar.gz"
      sha256 "0de4947741c9096f8aaaf06be7b90185cc2da3b5e1507eec48d1dbd20cc7145d"

      define_method(:install) do
        bin.install "daxtack-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ankit-py/daxtack-agent/releases/download/v1.0-rc1/daxtack-agent_Darwin_arm64.tar.gz"
      sha256 "d270b511281769f08c5aefbfc641f09d9f377a4defaa33fe831fa317bc8920f4"

      define_method(:install) do
        bin.install "daxtack-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ankit-py/daxtack-agent/releases/download/v1.0-rc1/daxtack-agent_Linux_x86_64.tar.gz"
      sha256 "f5ed9bf6c218296b6e7e53b79ca9f120ed3c1e2c4537b7114c6c5df1893dfd7a"
      define_method(:install) do
        bin.install "daxtack-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ankit-py/daxtack-agent/releases/download/v1.0-rc1/daxtack-agent_Linux_arm64.tar.gz"
      sha256 "0cd453a20c54a91d633e4912c4a9834fb85576e0eb4fe13bb422b549da1f13ef"
      define_method(:install) do
        bin.install "daxtack-agent"
      end
    end
  end

  test do
    system "#{bin}/daxtack-agent version"
  end
end
